export const CART_ADD_MOBILE_TO_LOCAL_BEGIN = 'CART_ADD_MOBILE_TO_LOCAL_BEGIN';

export const CART_ADD_MOBILE_TO_LOCAL_SUCCESS =
  'CART_ADD_MOBILE_TO_LOCAL_SUCCESS';

export const CART_ADD_MOBILE_TO_LOCAL_ERROR = 'CART_ADD_MOBILE_TO_LOCAL_ERROR';

export const CART_INC_DEC_QUANTITY_BEGIN = 'CART_INC_DEC_QUANTITY_BEGIN';

export const CART_INC_DEC_QUANTITY_SUCCESS = 'CART_INC_DEC_QUANTITY_SUCCESS';

export const CART_REMOVE_ITEM_BEGIN = 'CART_REMOVE_ITEM_BEGIN';
export const CART_REMOVE_ITEM_SUCCESS = 'CART_REMOVE_ITEM_SUCCESS';

export const CART_REMOVE_ITEMS_SUCCESS = 'CART_REMOVE_ITEMS_SUCCESS';
