export const FILTER_MOBILE_GET_ALL = 'FILTER_MOBILE_GET_ALL';

export const FILTER_MOBILE_SET = 'FILTER_MOBILE_SET';

export const FILTER_MOBILE_SORT = 'FILTER_MOBILE_SORT';

export const FILTER_MOBILE_BY_KEYWORD = 'FILTER_MOBILE_BY_KEYWORD';

export const FILTER_MOBILE_BY_BRAND = 'FILTER_MOBILE_BY_BRAND';

export const FILTER_MOBILE_BY_STAR = 'FILTER_MOBILE_BY_STAR';

export const FILTER_MOBILE_BY_PRICE = 'FILTER_MOBILE_BY_PRICE';

export const FILTER_MOBILE_BY_RAM = 'FILTER_MOBILE_BY_RAM';

export const FILTER_MOBILE_BY_COLOR = 'FILTER_MOBILE_BY_COLOR';

export const FILTER_MOBILE_BY_MOVILSHOP_ASSURED =
  'FILTER_MOBILE_BY_MOVILSHOP_ASSURED';

export const FILTER_MOBILE_CLEAR = 'FILTER_MOBILE_CLEAR';
