export const MOBILE_CREATE_BEGIN = 'MOBILE_CREATE_BEGIN';
export const MOBILE_CREATE_SUCCESS = 'MOBILE_CREATE_SUCCESS';
export const MOBILE_CREATE_ERROR = 'MOBILE_CREATE_ERROR';

export const MOBILE_LIST_BEGIN = 'MOBILE_LIST_BEGIN';
export const MOBILE_LIST_SUCCESS = 'MOBILE_LIST_SUCCESS';
export const MOBILE_LIST_ERROR = 'MOBILE_LIST_ERROR';

export const MOBILE_GET_BEGIN = 'MOBILE_GET_BEGIN';
export const MOBILE_GET_SUCCESS = 'MOBILE_GET_SUCCESS';
export const MOBILE_GET_ERROR = 'MOBILE_GET_ERROR';

export const MOBILE_CLEAR_SAVED = 'MOBILE_CLEAR_SAVED';

export const MOBILE_GIVE_REVIEW_BEGIN = 'MOBILE_GIVE_REVIEW_BEGIN';
export const MOBILE_GIVE_REVIEW_SUCCESS = 'MOBILE_GIVE_REVIEW_SUCCESS';
export const MOBILE_GIVE_REVIEW_ERROR = 'MOBILE_GIVE_REVIEW_ERROR';

export const MOBILE_UPDATE_REVIEW_BEGIN = 'MOBILE_UPDATE_REVIEW_BEGIN';
export const MOBILE_UPDATE_REVIEW_SUCCESS = 'MOBILE_UPDATE_REVIEW_SUCCESS';
export const MOBILE_UPDATE_REVIEW_ERROR = 'MOBILE_UPDATE_REVIEW_ERROR';
