// Crate an Order, razorpay
export const PAYMENT_RAZORPAY_CREATE_AN_ORDER_BEGIN =
  'PAYMENT_RAZORPAY_CREATE_AN_ORDER_BEGIN';

export const PAYMENT_RAZORPAY_CREATE_AN_ORDER_SUCCESS =
  'PAYMENT_RAZORPAY_CREATE_AN_ORDER_SUCCESS';

export const PAYMENT_RAZORPAY_CREATE_AN_ORDER_ERROR =
  'PAYMENT_RAZORPAY_CREATE_AN_ORDER_ERROR';

// Make Payment
export const PAYMENT_MAKE_BEGIN = 'PAYMENT_MAKE_BEGIN';
export const PAYMENT_MAKE_SUCCESS = 'PAYMENT_MAKE_SUCCESS';
export const PAYMENT_MAKE_ERROR = 'PAYMENT_MAKE_ERROR';

// Clear states
export const PAYMENT_CLEAR_STATE = 'PAYMENT_CLEAR_STATE';
