export const SELLER_MOBILE_LIST_BEGIN = 'SELLER_MOBILE_LIST_BEGIN';
export const SELLER_MOBILE_LIST_SUCCESS = 'SELLER_MOBILE_LIST_SUCCESS';
export const SELLER_MOBILE_LIST_ERROR = 'SELLER_MOBILE_LIST_ERROR';

export const SELLER_MOBILE_DELETE_BEGIN = 'SELLER_MOBILE_DELETE_BEGIN';
export const SELLER_MOBILE_DELETE_SUCCESS = 'SELLER_MOBILE_DELETE_SUCCESS';
export const SELLER_MOBILE_DELETE_ERROR = 'SELLER_MOBILE_DELETE_ERROR';

export const SELLER_MOBILE_UPDATE_BEGIN = 'SELLER_MOBILE_UPDATE_BEGIN';
export const SELLER_MOBILE_UPDATE_SUCCESS = 'SELLER_MOBILE_UPDATE_SUCCESS';
export const SELLER_MOBILE_UPDATE_ERROR = 'SELLER_MOBILE_UPDATE_ERROR';

export const SELLER_CLEAR_STATE = 'SELLER_CLEAR_STATE';
