// Authenticate User
export const USER_AUTHENTICATION_SUCCESS = 'USER_AUTHENTICATION_SUCCESS';
export const USER_AUTHENTICATION_FAIL = 'USER_AUTHENTICATION_FAIL';

// Check is user registered
export const USER_REGISTER_CHECK_BEGIN = 'USER_REGISTER_CHECK_BEGIN';
export const USER_REGISTER_CHECK_SUCCESS = 'USER_REGISTER_CHECK_SUCCESS';
export const USER_REGISTER_CHECK_ERROR = 'USER_REGISTER_CHECK_ERROR';

// Custom login Actions
export const USER_SIGN_IN_BEGIN = 'USER_SIGN_IN_BEGIN';
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_IN_ERROR = 'USER_SIGN_IN_ERROR';

// Sign up actions
export const USER_SIGN_UP_BEGIN = 'USER_SIGN_UP_BEGIN';
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
export const USER_SIGN_UP_ERROR = 'USER_SIGN_UP_ERROR';

// CLEAR_MESSAGE
export const USER_CLEAR_SIGNUP_STATUS = 'USER_CLEAR_SIGNUP_STATUS';

// Account Info Action
export const USER_INFO_BEGIN = 'USER_INFO_BEGIN';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_ERROR = 'USER_INFO_ERROR';

// Custom User Log Out
export const USER_LOG_OUT_BEGIN = 'USER_LOG_OUT_BEGIN';
export const USER_LOG_OUT_SUCCESS = 'USER_LOG_OUT_SUCCESS';
export const USER_LOG_OUT_ERROR = 'USER_LOG_OUT_ERROR';

// Update User log constants
export const USER_UPDATE_BEGIN = 'USER_UPDATE_BEGIN';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_ERROR = 'USER_UPDATE_ERROR';

// Change Display picture
export const USER_CHANGE_DP_BEGIN = 'USER_CHANGE_DP_BEGIN';
export const USER_CHANGE_DP_SUCCESS = 'USER_CHANGE_DP_SUCCESS';
export const USER_CHANGE_DP_ERROR = 'USER_CHANGE_DP_ERROR';

// Change Display picture
export const USER_CART_ADD_MOBILE_BEGIN = 'USER_CART_ADD_MOBILE_BEGIN';
export const USER_CART_ADD_MOBILE_SUCCESS = 'USER_CART_ADD_MOBILE_SUCCESS';
export const USER_CART_ADD_MOBILE_ERROR = 'USER_CART_ADD_MOBILE_ERROR';

// CART CONSTANTS
export const USER_CART_ITEM_INC_DEC_QUANTITY_BEGIN =
  'USER_CART_ITEM_INC_DEC_QUANTITY_BEGIN';

export const USER_CART_ITEM_INC_DEC_QUANTITY_ERROR =
  'USER_CART_ITEM_INC_DEC_QUANTITY_ERROR';

export const USER_CART_ITEM_INC_DEC_QUANTITY_SUCCESS =
  'USER_CART_ITEM_INC_DEC_QUANTITY_SUCCESS';

export const USER_CART_ITEM_DELETE_BEGIN = 'USER_CART_ITEM_DELETE_BEGIN';
export const USER_CART_ITEM_DELETE_ERROR = 'USER_CART_ITEM_DELETE_ERROR';
export const USER_CART_ITEM_DELETE_SUCCESS = 'USER_CART_ITEM_DELETE_SUCCESS';

export const USER_CART_REMOVE_ALL_BEGIN = 'USER_CART_REMOVE_ALL_BEGIN';
export const USER_CART_REMOVE_ALL_SUCCESS = 'USER_CART_REMOVE_ALL_SUCCESS';
export const USER_CART_REMOVE_ALL_ERROR = 'USER_CART_REMOVE_ALL_ERROR';

// Save User delivery address
export const USER_DELIVERY_ADDRESS_SAVE_BEGIN =
  'USER_DELIVERY_ADDRESS_SAVE_BEGIN';

export const USER_DELIVERY_ADDRESS_SAVE_ERROR =
  'USER_DELIVERY_ADDRESS_SAVE_ERROR';

export const USER_DELIVERY_ADDRESS_SAVE_SUCCESS =
  'USER_DELIVERY_ADDRESS_SAVE_SUCCESS';

// Save Orders
export const USER_ORDERS_SAVE_BEGIN = 'USER_ORDERS_SAVE_BEGIN';
export const USER_ORDERS_SAVE_ERROR = 'USER_ORDERS_SAVE_ERROR';
export const USER_ORDERS_SAVE_SUCCESS = 'USER_ORDERS_SAVE_SUCCESS';
